drush cr
drush en admin_toolbar
drush en admin_toolbar_tools
drush en automated_cron
drush en block
drush en block_content
drush en breakpoint
drush en breakpoints_ui
drush en ckeditor
drush en color
drush en comment
drush en config
drush en config_translation
drush en config_update
drush en config_update_ui
drush en contact
drush en content_translation
drush en contextual
drush en crop
drush en datetime
drush en dblog
drush en devel
drush en devel_generate
drush en dynamic_page_cache
drush en easy_breadcrumb
drush en editor
drush en field
drush en field_group
drush en field_ui
drush en file
drush en filter
drush en help
drush en history
drush en image
drush en image_widget_crop
drush en kint
drush en language
drush en layout_discovery
drush en link
drush en locale
drush en menu_link_content
drush en menu_ui
drush en node
drush en options
drush en page_cache
drush en path
drush en pathauto
drush en quickedit
drush en rdf
drush en redirect
drush en responsive_image
drush en search
drush en shortcut
drush en simplenews
drush en system
drush en taxonomy
drush en taxonomy_menu
drush en text
drush en token
drush en toolbar
drush en tour
drush en user
drush en video_embed_field
drush en views
drush en views_ui
drush cr

