<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function btnutripal_preprocess_node(&$variables) {
	if($variables['node']->getType() == 'aliments'){
		$serving_calculator = \Drupal\block\Entity\Block::load('nutripalnutritionvaluescalculator');
		$serving_calculator_view = \Drupal::entityTypeManager()
		  ->getViewBuilder('block')
		  ->view($serving_calculator);
		if ($serving_calculator_view) {
		    $variables['serving_calculator'] = $serving_calculator_view;
		}

		$serving = \Drupal::request()->query->get('serving');
		$variables['serving'] = "100 g";
		$variables['#cache']['max-age'] = 1;
		if(isset($serving)){
			$variables['serving'] = $serving." g";
			$variables['content']['field_calories'][0]['#markup'] = round((floatVal($variables['content']['field_calories'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_calcium'][0]['#markup'] = round((floatVal($variables['content']['field_calcium'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_carbohydrate'][0]['#markup'] = round((floatVal($variables['content']['field_carbohydrate'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_cholesterol'][0]['#markup'] = round((floatVal($variables['content']['field_cholesterol'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_total_fat'][0]['#markup'] = round((floatVal($variables['content']['field_total_fat'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_fiber'][0]['#markup'] = round((floatVal($variables['content']['field_fiber'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_iron'][0]['#markup'] = round((floatVal($variables['content']['field_iron'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_monounsaturated_fat'][0]['#markup'] = round((floatVal($variables['content']['field_monounsaturated_fat'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_polyunsaturated_fat'][0]['#markup'] = round((floatVal($variables['content']['field_polyunsaturated_fat'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_potassium'][0]['#markup'] = round((floatVal($variables['content']['field_potassium'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_protein'][0]['#markup'] = round((floatVal($variables['content']['field_protein'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_saturated_fat'][0]['#markup'] = round((floatVal($variables['content']['field_saturated_fat'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_sodium'][0]['#markup'] = round((floatVal($variables['content']['field_sodium'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_sugar'][0]['#markup'] = round((floatVal($variables['content']['field_sugar'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_vitamin_a'][0]['#markup'] = round((floatVal($variables['content']['field_vitamin_a'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_vitamin_b'][0]['#markup'] = round((floatVal($variables['content']['field_vitamin_b'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_vitamin_c'][0]['#markup'] = round((floatVal($variables['content']['field_vitamin_c'][0]['#markup'])/100)*floatVal($serving), 2);
			$variables['content']['field_vitamin_d'][0]['#markup'] = round((floatVal($variables['content']['field_vitamin_d'][0]['#markup'])/100)*floatVal($serving), 2);
		}
	}
}

function btnutripal_page_attachments_alter(array &$page) {
	
	$node = \Drupal::routeMatch()->getParameter('node');
	if (is_object($node) && $node != null && $node->getType() == 'aliments') {

	    $fat= $node->field_total_fat->value;
	    $protein = $node->field_protein->value;
	    $carbohydrate = $node->field_carbohydrate->value;

	    $page['#attached']['drupalSettings']['nutripal']['values']['fat'] =  $fat;
	    $page['#attached']['drupalSettings']['nutripal']['values']['protein'] =  $protein;
	    $page['#attached']['drupalSettings']['nutripal']['values']['carbohydrate'] =  $carbohydrate;
	}
}
